[package]
name = "rabbitmonitor"
version = "0.1.0"
authors = ["Rabbit Company LLC"]
description = "Simple server monitor"
edition = "2021"
categories = ["command-line-utilities"]
repository = "https://github.com/Rabbit-Company/RabbitMonitor"
keywords = ["cli", "process-monitoring"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.2", features = ["derive"] }
rocket = "=0.5.0-rc.3"
sysinfo = "0.28.4"
