[package]
name = "rabbitmonitor"
version = "3.1.0"
authors = ["Rabbit Company LLC <info@rabbit-company.com>"]
description = "Simple server monitor"
edition = "2021"
repository = "https://github.com/Rabbit-Company/RabbitMonitor2"
license = "GPL-3.0"
readme = "README.md"
rust-version = "1.68.2"
categories = ["command-line-utilities"]
keywords = ["cli", "process-monitoring"]
publish = ["rabbitmonitor"]

[dependencies]
clap = { version = "4.2.4", features = ["derive"] }
rocket = "=0.5.0-rc.3"
sysinfo = "0.28.4"
